#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare anituner for snap
#
# Date: Aug 27 2018
#

dlatun () {
    wget http://download.gdgsoft.com/anitun2p.zip &> /dev/null
}

mkatun () {
    mkdir -p ./{wine-runtime,wine-platform,bin} && mkdir -p usr/share/{pixmaps,applications}
    unzip anitun2p.zip -d "usr/share/anituner" &> /dev/null
    rm *.zip && cp usr/share/anituner/AniTuner.exe usr/share/anituner/anituner.exe && rm usr/share/anituner/AniTuner.exe
    find "usr" -type d -execdir chmod 755 {} +
}

dlatun
mkatun
mv anituner bin && mv anituner.desktop usr/share/applications && mv anituner.png usr/share/pixmaps && cp -R -p {bin,usr,wine-runtime,wine-platform} $SNAPCRAFT_PART_INSTALL